version: '3'
services:
  xdebug3:
    image: e4stjun/xdebug3:latest
    container_name: xdebug3
    build:
      context: xdebug3
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html/:rw
      - ./conf:/etc/apache2/sites-enabled/
      - ./xdebug3/ini/:/usr/local/etc/php/conf.d/
    environment:
      - TZ=Asia/Shanghai
  db:
    image: mysql:8.0.33
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: e4stjun
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: cms
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
